### ISSUE TITLE
Remove coronavirusdatamap.com and californiacoronavirus.org

### ISSUE THREAD

**Issue by embreinhardt** [merkleID/covid-domains#1]
I'm the developer behind coronavirusdatamap.com and californiacoronavirus.org. Both sites are dashboards to view vetted coronavirus data directly from the NY Times and SF Chronicle. They ask for no user information. I've heard from some of my users who rely on this data that they're seeing it blocked. Please consider removing it from this list. Thanks!

**Comment by merkleID** [comment]
Hi
I’ll do it immediately 

Sorry for any annoyance

Luca F. Perozzo

**Comment by embreinhardt** [comment]
Thank you so much!

**Comment by merkleID** [comment]
Done!

Took a little as it’s a bash script so I had to create a routine to parse the exclusion list and then parse over and over the same file to remove any line.

Feel free to contact me for any other inconvenience.

Cheers,
Luca F. Perozzo

**Comment by embreinhardt** [comment]
Thanks so much! Appreciate it!
